export const SPECIES = [
  {
    id: "orman",
    name: "Orman Şapkası",
    kind: "forest",
    desc: "Dengeli büyüme. Balistik spor atışı, momentumlu dallanan kök ağı (DLA).",
    color: 0xc96a3b,
    stemColor: 0xecdcc0,
    mycColor: 0xc08a52,
    emissive: 0x000000,
    halo: false,
    growthTime: 26,
    height: 1.6,
    lifetime: 150,
    sporeInterval: 5,
    sporeRange: 6,
    sporeChance: 0.5,
    burst: 1,
    myceliumRate: 6,
    aggression: 5,
    pulseSpeed: 2.2,
    maxCount: 260,
    spreadKernel: "ballistic",
    momentum: 0.35,
    puff: false,
    ring: false,
    vs: { parazit: 1 },
  },
  {
    id: "slime",
    name: "Slime Mantarı",
    kind: "slime",
    desc: "Yapışkan zarla çevreye sıçrar (splash), toprağı kaplar. Saldırgan.",
    color: 0x9fdf6f,
    stemColor: 0x7fcb55,
    mycColor: 0x6fce4f,
    emissive: 0x3f9b2f,
    halo: false,
    growthTime: 14,
    height: 1.0,
    lifetime: 220,
    sporeInterval: 9,
    sporeRange: 3,
    sporeChance: 0.55,
    burst: 1,
    myceliumRate: 20,
    aggression: 9,
    pulseSpeed: 3.1,
    maxCount: 200,
    spreadKernel: "splash",
    momentum: 0,
    puff: false,
    ring: false,
    vs: { orman: 2, mercan: 2 },
  },
  {
    id: "mercan",
    name: "Mercan Fungus",
    kind: "coral",
    desc: "Rüzgar kerneliyle (wind) çok uzak mesafelere spor atar, yavaş dev yapı.",
    color: 0xff8a5c,
    stemColor: 0xffb48a,
    mycColor: 0xe0704a,
    emissive: 0x000000,
    halo: false,
    growthTime: 60,
    height: 4.5,
    lifetime: 320,
    sporeInterval: 16,
    sporeRange: 18,
    sporeChance: 0.3,
    burst: 1,
    myceliumRate: 2.6,
    aggression: 3,
    pulseSpeed: 1.3,
    maxCount: 150,
    spreadKernel: "wind",
    momentum: 0.15,
    puff: false,
    ring: false,
    fatTail: 0.05,
  },
  {
    id: "isik",
    name: "Işık Şapkası",
    kind: "glowcap",
    desc: "Biyolüminesan. Balistik spor, halo ışığı ve sık sinyal yayımı.",
    color: 0x7ef0ff,
    stemColor: 0xbff4ff,
    mycColor: 0x4fd8f0,
    emissive: 0x37e0ff,
    halo: true,
    growthTime: 20,
    height: 1.4,
    lifetime: 170,
    sporeInterval: 4,
    sporeRange: 9,
    sporeChance: 0.45,
    burst: 1,
    myceliumRate: 8,
    aggression: 5,
    pulseSpeed: 2.8,
    maxCount: 240,
    spreadKernel: "ballistic",
    momentum: 0.1,
    puff: false,
    ring: false,
  },
  {
    id: "parazit",
    name: "Parazit Ağı",
    kind: "parasite",
    desc: "Sporları kendi kök ağı içinde teleport eder (network), rakipleri ele geçirir.",
    color: 0x8a4fe8,
    stemColor: 0xa87ff0,
    mycColor: 0x7a3fd6,
    emissive: 0x3a1f6e,
    halo: false,
    growthTime: 10,
    height: 1.2,
    lifetime: 95,
    sporeInterval: 2.4,
    sporeRange: 8,
    sporeChance: 0.8,
    burst: 2,
    myceliumRate: 15,
    aggression: 12,
    pulseSpeed: 4.2,
    maxCount: 260,
    spreadKernel: "network",
    momentum: 0.2,
    puff: false,
    ring: false,
    vs: { slime: 2, inkcap: 2 },
  },
  {
    id: "dev",
    name: "Dev Kubbe",
    kind: "giant",
    desc: "Çok yavaş, kocaman. Kitlesel spor patlamaları, rüzgar taşımacılığı.",
    color: 0xd8a45f,
    stemColor: 0xf0e0c0,
    mycColor: 0xa97c44,
    emissive: 0x000000,
    halo: false,
    growthTime: 120,
    height: 5.5,
    lifetime: 640,
    sporeInterval: 10,
    sporeRange: 22,
    sporeChance: 1,
    burst: 14,
    myceliumRate: 2,
    aggression: 7,
    pulseSpeed: 1.0,
    maxCount: 40,
    spreadKernel: "wind",
    momentum: 0,
    puff: false,
    ring: false,
    fatTail: 0.04,
    vs: { parazit: 3 },
  },
  {
    id: "physarum",
    name: "Physarum Ağı",
    kind: "physarum",
    desc: "Slime mold: damar benzeri kök ağı (momentum), network spor taşımacılığı.",
    color: 0xf5d442,
    stemColor: 0xffe98a,
    mycColor: 0xe8c23a,
    emissive: 0x8a6d00,
    halo: false,
    growthTime: 16,
    height: 1.0,
    lifetime: 200,
    sporeInterval: 6,
    sporeRange: 7,
    sporeChance: 0.4,
    burst: 1,
    myceliumRate: 12,
    aggression: 4,
    pulseSpeed: 3.5,
    maxCount: 220,
    spreadKernel: "network",
    momentum: 0.75,
    puff: false,
    ring: false,
    prune: true,
  },
  {
    id: "inkcap",
    name: "Mürekkep Mantarı",
    kind: "inkcap",
    desc: "Peri halkası (fairy ring): koloni kenarındaki dalga hattında meyve verir.",
    color: 0x4a4a55,
    stemColor: 0xe8e4d8,
    mycColor: 0x8a8a96,
    emissive: 0x000000,
    halo: false,
    growthTime: 24,
    height: 2.2,
    lifetime: 120,
    sporeInterval: 7,
    sporeRange: 4,
    sporeChance: 0.5,
    burst: 1,
    myceliumRate: 4,
    aggression: 4,
    pulseSpeed: 1.8,
    maxCount: 180,
    spreadKernel: "splash",
    momentum: 0,
    puff: false,
    ring: true,
    recycle: true,
  },
  {
    id: "puffball",
    name: "Puf Topu",
    kind: "puffball",
    desc: "Calvatia: uzun olgunlaşma, sonra tek seferde kitlesel spor bulutu ve ölüm.",
    color: 0xefe9d8,
    stemColor: 0xd9d0b8,
    mycColor: 0xcfc6ac,
    emissive: 0x000000,
    halo: false,
    growthTime: 70,
    height: 1.6,
    lifetime: 300,
    sporeInterval: 12,
    sporeRange: 10,
    sporeChance: 0.5,
    burst: 60,
    myceliumRate: 2.5,
    aggression: 3,
    pulseSpeed: 0.8,
    maxCount: 30,
    spreadKernel: "ballistic",
    momentum: 0,
    puff: true,
    ring: false,
  },
  {
    id: "earthstar",
    name: "Yer Yıldızı",
    kind: "earthstar",
    desc: "Geastrum: yıldız kolları topraktan açılır, splash kernel ile dağılır.",
    color: 0xb5654a,
    stemColor: 0xd8a67e,
    mycColor: 0xa0522d,
    emissive: 0x000000,
    halo: false,
    growthTime: 40,
    height: 0.7,
    lifetime: 180,
    sporeInterval: 9,
    sporeRange: 3,
    sporeChance: 0.5,
    burst: 1,
    myceliumRate: 5,
    aggression: 5,
    pulseSpeed: 1.6,
    maxCount: 120,
    spreadKernel: "splash",
    momentum: 0,
    puff: false,
    ring: false,
  },
];
