export const SPECIES = [
  {
    id: "orman",
    name: "Orman Şapkası",
    kind: "forest",
    desc: "Dengeli büyüme. Orta menzilli spor salınımı, klasik kök ağı.",
    color: 0xc96a3b,
    stemColor: 0xecdcc0,
    mycColor: 0xc08a52,
    emissive: 0x000000,
    halo: false,
    growthTime: 26,
    height: 1.6,
    lifetime: 150,
    sporeInterval: 5,
    sporeRange: 6,
    sporeChance: 0.5,
    burst: 1,
    myceliumRate: 6,
    aggression: 5,
    pulseSpeed: 2.2,
    maxCount: 260,
  },
  {
    id: "slime",
    name: "Slime Mantarı",
    kind: "slime",
    desc: "Yapışkan zarla hızlı yayılır, toprağı kaplar. Uzun ömürlü, saldırgan.",
    color: 0x9fdf6f,
    stemColor: 0x7fcb55,
    mycColor: 0x6fce4f,
    emissive: 0x3f9b2f,
    halo: false,
    growthTime: 14,
    height: 1.0,
    lifetime: 220,
    sporeInterval: 9,
    sporeRange: 3,
    sporeChance: 0.55,
    burst: 1,
    myceliumRate: 20,
    aggression: 9,
    pulseSpeed: 3.1,
    maxCount: 200,
  },
  {
    id: "mercan",
    name: "Mercan Fungus",
    kind: "coral",
    desc: "Yavaş ama devasa büyür. Rüzgarla çok uzak mesafelere spor atar.",
    color: 0xff8a5c,
    stemColor: 0xffb48a,
    mycColor: 0xe0704a,
    emissive: 0x000000,
    halo: false,
    growthTime: 60,
    height: 4.5,
    lifetime: 320,
    sporeInterval: 16,
    sporeRange: 18,
    sporeChance: 0.3,
    burst: 1,
    myceliumRate: 2.6,
    aggression: 3,
    pulseSpeed: 1.3,
    maxCount: 150,
  },
  {
    id: "isik",
    name: "Işık Şapkası",
    kind: "glowcap",
    desc: "Biyolüminesan. Sık spor üretir, karanlıkta parlar ve sinyal yayar.",
    color: 0x7ef0ff,
    stemColor: 0xbff4ff,
    mycColor: 0x4fd8f0,
    emissive: 0x37e0ff,
    halo: true,
    growthTime: 20,
    height: 1.4,
    lifetime: 170,
    sporeInterval: 4,
    sporeRange: 9,
    sporeChance: 0.45,
    burst: 1,
    myceliumRate: 8,
    aggression: 5,
    pulseSpeed: 2.8,
    maxCount: 240,
  },
  {
    id: "parazit",
    name: "Parazit Ağı",
    kind: "parasite",
    desc: "Saldırgan kolonizatör. Kök ağı yangın gibi yayılır, rakipleri ele geçirir.",
    color: 0x8a4fe8,
    stemColor: 0xa87ff0,
    mycColor: 0x7a3fd6,
    emissive: 0x3a1f6e,
    halo: false,
    growthTime: 10,
    height: 1.2,
    lifetime: 95,
    sporeInterval: 2.4,
    sporeRange: 8,
    sporeChance: 0.8,
    burst: 2,
    myceliumRate: 15,
    aggression: 12,
    pulseSpeed: 4.2,
    maxCount: 260,
  },
  {
    id: "dev",
    name: "Dev Kubbe",
    kind: "giant",
    desc: "Çok yavaş, kocaman. Seyrek ama kitlesel spor patlamalarıyla çoğalır.",
    color: 0xd8a45f,
    stemColor: 0xf0e0c0,
    mycColor: 0xa97c44,
    emissive: 0x000000,
    halo: false,
    growthTime: 120,
    height: 5.5,
    lifetime: 640,
    sporeInterval: 10,
    sporeRange: 22,
    sporeChance: 1,
    burst: 14,
    myceliumRate: 2,
    aggression: 7,
    pulseSpeed: 1.0,
    maxCount: 40,
  },
];
